server:
  port: 8080

spring:
  application:
    name: psp-service

operator:
  base-url: http://localhost:8080
  version: v1
  signing-version: "2"
  psp:
    token: your-psp-token
    id: your-psp-id
  timeout:
    connection: 5000      # Connection timeout in milliseconds (5 seconds)
    read: 30000          # Read timeout in milliseconds (30 seconds)
    write: 30000         # Write timeout in milliseconds (30 seconds)
    response: 60000      # Response timeout in milliseconds (60 seconds)