server:
  port: 8080

spring:
  application:
    name: psp-service
  
  # Oracle Database Configuration
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: psp_user
    password: psp_password
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        
  # Cache Configuration
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10,expireAfterAccess=7d

operator:
  base-url: http://localhost:8080
  version: v1
  signing-version: "2"
  psp:
    token: your-psp-token
    id: your-psp-id
  timeout:
    connection: 5000      # Connection timeout in milliseconds (5 seconds)
    read: 30000          # Read timeout in milliseconds (30 seconds)
    write: 30000         # Write timeout in milliseconds (30 seconds)
    response: 60000      # Response timeout in milliseconds (60 seconds)

# Merchant Provider Configuration
merchant:
  provider: "demirbank"  # Provider identifier for direction determination
  # Supported providers:
  # - "demirbank" - Uses internal bank client for transactions
  # - Any other value - Uses external operator client for transactions

# QR Decoder Configuration
qr:
  decoder:
    base-url: ""  # For future external QR decoder service

# Bank Service Configuration  
bank:
  service:
    base-url: ""  # For future bank service integration

security:
  signature:
    operator-public-key-path: /path/to/operator-public-key.pem
    psp-private-key-path: /path/to/psp-private-key.pem
    enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    kg.demirbank.psp: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
  file:
    name: logs/psp-service.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB
  logback:
    rollingpolicy:
      file-name-pattern: logs/psp-service.%d{yyyy-MM-dd}.%i.log